### ISSUE TITLE
Formatting subtitle in plotBin

### ISSUE THREAD

**Issue by PTesta** [bquast/rddtools#3]
I think you only want one backslash for the tab, so \tn instead of \\\\tn on line 64:

`  title(main = main, sub = paste("h=", round(h, 4), ",\tn bins=", n_non0_intervs, sep = ""))`

instead of:

`  title(main = main, sub = paste("h=", round(h, 4), ",\\tn bins=", n_non0_intervs, sep = ""))`

**Comment by bquast** [comment]
Could you please submit a pull request?

**Comment by PTesta** [comment]
Yes! Sorry, I'm not the most gitliterate. Thanks for the great package

**Comment by bquast** [comment]
merge per #4

**Comment by bquast** [comment]
Hi Paul,

I added a post in which I mentioned your bugfix, with a link to your site. I hope you don't mind, otherwise please do let me know. Thanks again!

Bastiaan

http://qua.st/rddtools/updates-coming

**Comment by PTesta** [comment]
Thanks Bastiaan! That's totally unnecessary but very kind and I appreciate
the link! I also really appreciate the package, and your personal site,
which is a gold mine of resources. Keep up the good work!

Best,
Paul
