### ISSUE TITLE
rddtools on R4?

### ISSUE THREAD

**Issue by axlehner** [bquast/rddtools#9]
Hi,
I was just wondering whether you plan to fix the check problem to get the package on CRAN again for R4? A package of mine potentially is going to depend on it (plus it would depend on the rddapp that partly depends on yours I learned).
Would be a pitty if not, it is a cool package!

Cheers

**Comment by MatthieuStigler** [comment]
Hi

Yes, sorry for this! We had corrected it and a new issue came, now with:  

```
Error in ks.test(x[regime], x[!regime], exact = exact) : 
     not enough 'x' data
```
@bquast this is something I will try to fix, or eventually remove this feature which is not essential. I will try to do this in the next few days.

**Comment by MatthieuStigler** [comment]
we published a new version on CRAN! https://cran.r-project.org/web/packages/rddtools/index.html
